apiVersion: v1
kind: Service
metadata:
  name: ares-global
  namespace: {{ .Values.namespace }}
  labels:
    app: ares-global
    {{- include "ares-global.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.scheduler.port }}
      name: http
      protocol: TCP
  selector:
    app: ares-global
